### ISSUE TITLE
conditional return

### ISSUE THREAD

**Issue by timofei7** [Naman-Goyal/DaliMembersApp#1]
https://github.com/Naman-Goyal/DaliMembersApp/blob/0ed0d8d669da2432918eee65587158322a9701da/app/src/main/java/me/namangoyal/dalimembers/DaliMember.kt#L46

how could this be simplified?   hint: what does a conditional evaluate to - ie what does (foo == bar) evaluate to?

**Comment by kala-goyal** [comment]
Do you mean something more like this?

https://gist.github.com/Naman-Goyal/27d01fc99869c417dbfd64a8a9e71a3e

**Comment by timofei7** [comment]
yup!  exactly like that - much cleaner that way.

**Comment by kala-goyal** [comment]
Ok, pushing changes
