### ISSUE TITLE
clicking on name tag in map only sometimes opens profile view

### ISSUE THREAD

**Issue by timofei7** [Naman-Goyal/DaliMembersApp#2]

**Comment by kala-goyal** [comment]
I've put it to work on double-clicking within one second. Does it not work even on double clicks?

**Comment by timofei7** [comment]
aaa, double click explains it - it does work but generally double clicks are very uncommon in mobile - the ux of them too often feel like only works some of the time - ("why does it take multiple clicks sometimes".   i'd just make it a single click as that is much more common.

**Comment by kala-goyal** [comment]
ah, that makes sense. It makes the code cleaner as well. I've changed it.
